import { invoke } from "@tauri-apps/api/core";
import { homeDir } from "@tauri-apps/api/path";
export type SkillScope = "global" | "project";
export interface Skill { id:string; name:string; description:string; body:string; path:string; scope:SkillScope; enabled:boolean; agents:string[]; source:SkillScope; }
type SkillSettings = Record<string,{enabled?:boolean;agents?:string[]}>;
const STORAGE_KEY="andro.skills.settings.v1";
function settings():SkillSettings{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");}catch{return {};}}
function parseFrontmatter(raw:string){if(!raw.startsWith("---"))return{meta:{},body:raw.trim()};const end=raw.indexOf("\n---",3);if(end<0)return{meta:{},body:raw.trim()};const meta:Record<string,string>={};for(const line of raw.slice(4,end).split(/\r?\n/)){const m=line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(m)meta[m[1].toLowerCase()]=m[2].trim().replace(/^['"]|['"]$/g,"");}return{meta,body:raw.slice(end+4).replace(/^\n/,"").trim()};}
async function entries(path:string):Promise<Array<{name:string;path:string;is_dir:boolean}>>{try{return await invoke("list_directory",{path});}catch{return[];}}
async function scanRoot(path:string,scope:SkillScope):Promise<Skill[]>{const list=await entries(path);const dirs=list.filter(e=>e.is_dir&&!e.name.startsWith("."));const files=list.filter(e=>!e.is_dir&&e.name.toLowerCase()==="skill.md");const candidates=[...dirs.map(d=>({path:d.path,name:d.name})),...files.map(f=>({path:f.path,name:"skill"}))];const out:Skill[]=[];for(const c of candidates){const skillPath=c.path.toLowerCase().endsWith("skill.md")?c.path:c.path.replace(/[\\/]$/,"")+"/SKILL.md";let raw:string;try{raw=await invoke("read_file",{path:skillPath});}catch{continue;}const {meta,body}=parseFrontmatter(raw);const id=meta.id||c.name.toLowerCase().replace(/[^a-z0-9_-]+/g,"-");const saved=settings()[id];const agents=(meta.agents||"").split(",").map(x=>x.trim()).filter(Boolean);out.push({id,name:meta.name||c.name,description:meta.description||body.split("\n").find(Boolean)?.slice(0,160)||"",body,path:skillPath,scope,enabled:saved?.enabled??true,agents:saved?.agents??agents,source:scope});}return out;}
export async function discoverSkills(projectPath?:string):Promise<Skill[]>{const home=await homeDir();const roots=[scanRoot(home.replace(/[\\/]$/g,"")+"/.andro/skills","global")];if(projectPath)roots.push(scanRoot(projectPath.replace(/[\\/]$/g,"")+"/.andro/skills","project"));const groups=await Promise.all(roots);const merged=new Map<string,Skill>();for(const skill of groups.flat())merged.set(skill.id,skill);return[...merged.values()].sort((a,b)=>a.name.localeCompare(b.name));}
export function updateSkillSettings(skill:Skill,patch:Partial<Pick<Skill,"enabled"|"agents">>):void{const all=settings();all[skill.id]={...all[skill.id],...patch};localStorage.setItem(STORAGE_KEY,JSON.stringify(all));}
export function skillPromptContext(skills:Skill[],agentId?:string):string{return skills.filter(s=>s.enabled&&(!agentId||s.agents.length===0||s.agents.includes(agentId))).map(s=>`## Skill: ${s.name}\n${s.body}`).join("\n\n");}
